### PR TITLE
Show 'amount too big' error message

### LINKED ISSUE #8: No visible feedback when provided amount is too big
When a user inserts a high value (ex: 2 L-BTC), the console generates an error stating "provided amount is too big".
But the error shown to the user is the default one, "Preview not available".
Wouldn't it be better if we show the user the exact cause of the problem?

### PR DESCRIPTION
**Pull request by bordalix**
Fixes #8 

Error message is shown on TraderButton (as the others).
Button stays inactive with this error.

### CODE REVIEW

**Comment by tiero** [comment]
Looking at the error message can be fragile ie. the backend changes text or the dex is connected to a different backend that uses a different implementation of the tdex [protocol](https://github.com/tdex-network/tdex-daemon) (which does not standardize error code or messages at all).

We should actually have a proper error visualization interface to show in clear the message throw-ed, since we cannot know in advance all the error messages a backend uses.

**Comment by bordalix** [comment]
Agree, the protocol should standardise error codes and messages. In the meantime, I think is better to give the error message to the user, and change it after/when protocol change or if used with a different backend.

**Comment by tiero** [comment]
> Agree, the protocol should standardise error codes and messages.

Not sure this happens, ideally many different implementation of provider may have different uses cases, so is hard to say. 

Why not lifting up the error? We may need to introduce new UI for error and messages in general (maybe toasts?) instead of trying to fit all in the button.

In this scenario I wuold leave "Preview not available" as tradeButton message and throw a toast component on top right.

**Comment by bordalix** [comment]
Superseded by #19.
Closing.

**Pull request closed without merging**
